spring:
  datasource:
#    url: jdbc:h2:tcp://localhost/~/prove2022
    url: jdbc:log4jdbc:h2:tcp://localhost/~/prove2022
#    url: jdbc:h2:file:./prove2022;MODE=MySQL;DB_CLOSE_DELAY=-1
    username: sa
    password:
#    driver-class-name: org.h2.Driver
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: none
#    properties:
#      hibernate:
##        show_sql: true
#        format_sql: true
#        hibernate.use_sql_comments : true
#logging.level:
#  org.hibernate.SQL: debug
##  org.hibernate.type: trace

mybatis:
#  type-aliases-package: com.lds.trackdayb.domain;com.lds.trackdayb.vo;com.lds.trackdayb.mvo;com.lds.trackdayb.dto;
  mapper-locations: mybatis/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true